# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MVVM-Clean-Flow-Skeleton' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-Clean-Flow-Skeleton

pod 'AFNetworking', '4.0.1'
pod 'ReactiveObjC', '3.1.1'
pod 'UICKeyChainStore', '2.2.0'

target 'MVVM-Clean-Flow-SkeletonTests' do
    inherit! :search_paths
    pod 'testPods'
end

end

